const list = [
    {
        id: -2,
        name: "Nàng Thơ",
        album: "NT",
        artist: "Hoàng Dũng",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646407342/MP3-Data/wtixsqdxegn3p7onimrr.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646407348/MP3-Data/yhhptvmhei3qi8xjx8lo.mp3",
    },
    {
        id: -1,
        name: "THẰNG ĐIÊN",
        album: "TD",
        artist: "JUSTATEE x PHƯƠNG LY",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646360895/MP3-Data/l0b0hjndrn3npms2ncok.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646360903/MP3-Data/irhl7ktwbdpqrjoo0ig9.mp3",
    },
    {
        id: 0,
        name: "Cash Cash",
        album: "CC",
        artist: "Hero feat. Christina Perri",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646522925/MP3-Data/ykcqv96opo8ojugfkjiy.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646522927/MP3-Data/xauedu7m3h6etr5vs9gs.mp3",
    },
    {
        id: 1,
        name: "Chẳng Thể Tìm Được Em",
        album: "CTTDE",
        artist: "PhucXp ft. Freak D",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646360894/MP3-Data/iln63zvwr5fwwndrpzjw.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646360902/MP3-Data/f2crswkgpy3u5764tahx.mp3",
    },
    {
        id: 2,
        name: "Thức Giấc",
        album: "TD",
        artist: " Da LAB x Freak D",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646360895/MP3-Data/zdmt0jvfuymzzt1eyy9r.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646360899/MP3-Data/erdi6rpajeb5vysmncdb.mp3",
    },
    {
        id: 3,
        name: "Ngày Đầu Tiên (Lofi Ver.)",
        album: "NDT",
        artist: "Đức Phúc x Freak D",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646522962/MP3-Data/entjbexqhwnogjg5dszi.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646522973/MP3-Data/hg4xzifafty8n8qkxezp.mp3",
    },
    {
        id: 4,
        name: "Đã Lỡ Yêu Em Nhiều",
        album: "DLYEN",
        artist: "JustaTee",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646360894/MP3-Data/ont6ygkqn8q2xz6otu4q.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646360900/MP3-Data/qz7p38elsxm4nprktdme.mp3"
    },
    {
        id: 5,
        name: "按下暂停你将变得",
        album: "按下暂停",
        artist: "清醒且墮落 Mei",
        image: "https://res.cloudinary.com/tratahuong01/image/upload/v1646407241/MP3-Data/xbumrh6ajz37v59460en.webp",
        audio: "https://res.cloudinary.com/tratahuong01/video/upload/v1646407245/MP3-Data/kpzwnag1uueo1axic7fk.mp3"
    },
]